function Ne2fig(X1, Y1, X2, Y2)
%CREATEFIGURE(X1, Y1, X2, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 19-Jun-2019 16:55:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',24);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2010.8 2015.15]);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Simulation','LineWidth',3);

% Create plot
plot(X2,Y2,'DisplayName','Observed','LineWidth',3);

% Create xlabel
xlabel('Time','FontSize',26.4);

% Create ylabel
ylabel('Ne','FontSize',26.4);

% Create legend
legend(axes1,'show');

