function Ne3fig(X1, Y1, X2, Y2, X3, Y3)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data

%  Auto-generated by MATLAB on 20-Jun-2019 15:23:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',24);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2010.8 2015.15]);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Observed data','Marker','*','LineWidth',4,...
    'Color',[0.501960813999176 0.501960813999176 0.501960813999176]);

% Create plot
plot(X2,Y2,'DisplayName','Simulation w/ environmental replication',...
    'LineWidth',4,...
    'Color',[0 0.498039215803146 0]);

% Create plot
plot(X3,Y3,'DisplayName','Simulation w/o environmental replication',...
    'LineWidth',4,...
    'LineStyle','--',...
    'Color',[0.749019622802734 0 0.749019622802734]);

% Create xlabel
xlabel('Time','FontSize',26.4);

% Create ylabel
ylabel('Ne','FontSize',26.4);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.431250000000001 0.78295852163611 0.47265625 0.131438721136767]);

