function Ne5(X1, Y1, X2, YMatrix1, YData1, XData1)
%CREATEFIGURE(X1, Y1, X2, YMATRIX1, YDATA1, XDATA1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  YMATRIX1:  matrix of y data
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata

%  Auto-generated by MATLAB on 01-Aug-2019 16:47:04

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',30);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2010.5 2016]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 5]);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'DisplayName','Observed Skyride plot','MarkerSize',10,...
    'Marker','*',...
    'LineWidth',3,...
    'Color',[0.313725501298904 0.313725501298904 0.313725501298904]);

% Create multiple lines using matrix input to plot
plot1 = plot(X2,YMatrix1,'LineWidth',6,'Parent',axes1);
set(plot1(1),'DisplayName','Simulation with env. replication');
set(plot1(2),'DisplayName','Simulation with 2 enhanced control times');
set(plot1(3),'DisplayName','Simulation with 2 control times');
set(plot1(4),'DisplayName','Simulation with 1 enhanced control time');
set(plot1(5),'DisplayName','Simulation with 1 control time',...
    'Color',[0.854901969432831 0.701960802078247 1]);

% Create patch
patch('Parent',axes1,'DisplayName','95% CI for Skyride','YData',YData1,...
    'XData',XData1,...
    'FaceAlpha',0.5,...
    'EdgeAlpha',0.5,...
    'FaceColor',[0.941176474094391 0.941176474094391 0.941176474094391]);

% Create xlabel
xlabel('Time','FontSize',33);

% Create ylabel
ylabel('Ne  (Effective Population Size)','FontSize',33);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.169921875000002 0.137630543215649 0.416406250000001 0.31959706959707]);

