function NeCasesfig(X1, Y1, Y2)
%CREATEFIGURE(X1, Y1, Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 19-Jun-2019 16:56:34

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YTick',[0 10000 20000],...
    'YColor',[0 0.447 0.741],...
    'FontSize',24);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[2010.8 2015.13]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 20000]);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Parent',axes1,'LineWidth',4);

% Create xlabel
xlabel('Time','FontSize',26.4);

% Create ylabel
ylabel('Cases','FontSize',26.4);

% Create axes
axes2 = axes('Parent',figure1,'HitTest','off','Color','none',...
    'YTick',[0 1 2],...
    'YColor',[0.85 0.325 0.098],...
    'YAxisLocation','right',...
    'FontSize',24);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[2010.8 2015.13]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[0 2]);
hold(axes2,'on');

% Create plot
plot(X1,Y2,'Parent',axes2,'LineWidth',4);

% Create ylabel
ylabel('Ne','FontSize',26.4);

